version: '2'
services:
    mozhotels-app:
        image: mozhotels
        external_links:
            - mozhotels-postgresql:postgresql
            - mozhotels-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/mozhotels
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    mozhotels-postgresql:
        extends:
            file: postgresql.yml
            service: mozhotels-postgresql
    mozhotels-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: mozhotels-elasticsearch
